runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /widt
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build
skip_files:
- ^(.*/)?#.*#$
- node_modules